### ISSUE TITLE
ABC

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#97] opened 2016-07-11 17:29 UTC
1. Personalized repeat interval does not change for existing contacts, should it?
2. **Feature.**  A  new position for the personalized repeat interval should be added on the Repeat list. If the user decides to change the repeat interval one time for a contact but after decides to set it back to the one personalized, he cannot. He has to change it from Personalize and that should normally change all the contacts repeat interval. 
3. The 'Sort' button's position and size make it very hard for the user to tap on it. 
4. Repeat interval in Post follow-up is set to standard even if you changed it via Personalize. It is modified to the one set in Personalize if you tap on a different CG and then tap back to the contact's CG. **Depends on pct. 1. If pct. 1 will be fixed this will also be fixed.**
5. In follow-up, if you modify any of the details ( CG, Where we Met and Notes) and tap on Dismiss the information are getting saved. The contact is moved to the selected CG but the repeat interval remains the one from the previous CG.
6. **Question:** I'm having trouble understanding the use for repeat interval. If I set a follow-up for the next 3 minutes, then the follow-up screen is displayed. Here you can either set a new follow-up or dismiss the follow-up. In the first case, repeat interval has no usability. In the last case, the contact appears as missed. Here is where the repeat interval has its use? If yes, then the user should be able to set a repeat interval for minutes/hours not only days/months.
At this moment, after you call/SMS/email a contact the next Alert is set, based on the repeat interval, to x days/months. So why does the user have the option to  tap on the Follow Up buttons, which change the Alert Time? It will, for sure, confuse the user having two different methods that do the same thing.
7. The date the next follow-up is set ( in Post Follow Up) for a missed contact is **x** days/months from the date the contact was missed. So for example, if a contact appears missed since 08.07.2016 and I call him on 11.07.2016 in Post Follow Up the Next Follow-Up will be on 08.08.2016 ( 1 month from 08.07.2016 not 1 month from 11.07.2016 ). It should be set to  **x** days/months from the moment you contact him.
8. App sometimes crashes if, when in **History/Missed section**, you open a missed contact, tap on **Back** button and then select **History**

**Comment by tudorsss** [comment] 2016-07-11 19:26
Hey @unleu:

For 1, no it should not.
For 2, I added the bug.
For 3, I added the bug.
For 4, this is not a bug; you have these already set up before changing the default value to a custom one.
For 5, I added the bug.
For 6, let's talk.
For 7, very good bug, I added it.

**Comment by unleu** [comment] 2016-07-12 10:10
@tudorsss added bug no 8

**Comment by tudorsss** [comment] 2016-07-12 23:05
OK @unleu, I think we can close this one out, thanks!

**Closed by tudorsss** 2016-07-12 23:05 UTC
